INSERT INTO role VALUES (1, 'ROLE_ADMIN');
INSERT INTO role VALUES (2, 'ROLE_USER');
INSERT INTO user VALUES (1, CURRENT_TIMESTAMP , CURRENT_TIMESTAMP, '$2a$10$NGilQD0th7Eua817kfNgW.Lf18KXJm24vkDU/BU6/3WtzdHy831HK', 'admin');
INSERT INTO user_roles VALUES (1, 1);
